### ISSUE TITLE
stack warning

### ISSUE THREAD

**Issue by djhurtgen** [alihaider1264/traffic-management#7]
Stack overflow error when running code. Warning on main() in Source.cpp:

"Function uses '80052' bytes of stack: exceeds/analyze:stacksize '16384'. Consider moving some data to heap."

Maybe it's an issue local to my solution?

![stack_warning](https://user-images.githubusercontent.com/88782623/153032519-1dc3d0f4-d7b9-420f-b836-8ce00574ccf9.png)

**Comment by alihaider1264** [comment]
@djhurtgen I do not see this error when I run it. Let us go over this later today.
Regarding other errors, I had fixed them in a branch which I have now merged in main. The branch is still active as I am working on it (not actively though).
You will need to update from main in order to get the latest from main branch.
